### ISSUE TITLE
PapilioDuo does not hold configuration in flash

### ISSUE THREAD

**Issue by bmentink** [jamesbowman/swapforth#53]
Hi,

I execute the following commands:

papilio-prog -v -f xilinx/j1-papilioduo.bit
python shell.py -h /dev/ttyUSB0

That works, but ...

I thought the 1st command would store the *.bit file to the SPI Flash, but when I power-cycle the board, and shell in again, nothing ... I have to re-program, then  shell  in again, before I am back in the Forth.

Any idea's: What am I missing?

Also is there any guide to downloading/installing the xilinx tools? I have no idea which package to install ...

**Comment by jamesbowman** [comment]
The Papilio forums would be a good place to ask these questions. Closing.
