### ISSUE TITLE
j1b does not have "init" vector

### ISSUE THREAD

**Issue by bmentink** [jamesbowman/swapforth#54]
Hi,
I am using j1b on the Papilio Duo, but I cannot get my toplevel Forth word to execute on boot as there is no "init" vector word as there was for the j1a ..

There is nothing in the j1b documentation to show me how to do this ..

**Comment by jamesbowman** [comment]
j1b has something slightly fancier. At startup it tries to find the word "cold" and executes it.
So to get your word executed on boot, add a definition:

    : cold myword ;

Closing.
