### ISSUE TITLE
Testing j1a on HX1K

### ISSUE THREAD

**Issue by AnttiLukats** [jamesbowman/swapforth#7]
Hi
if j1a.bin is loaded to board compatible to icestick, should something come out of the serial port?

https://hackaday.io/project/6636-iced-an-arduino-style-board-with-ice-fpga

with j1a.bin loaded the LEDS are on, but I see nothing on uart, is that normal?

**Comment by jamesbowman** [comment]
Yes, it should be talking on the serial port at 115200. One thing to check:
serial port DTR is used as a reset signal.

So, if your terminal program allows it, release the DTR signal. This
should let the CPU boot.

**Comment by AnttiLukats** [comment]
HA it works was indeed the terminal settings issue
